version: '4'

services:
  # database
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  
  # server
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres 

  # client
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres:

